name: Running Cypress Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        
jobs:
  build:
    runs-on: self-hosted
    steps:
#       - name: Checkout
#         uses: actions/checkout@v2  
      - run: npm run test
#       - name: Cypress run      
#         uses: cypress-io/github-action@v2
# #           start: npm start  
#       - run: npm install
#       - run: npx cypress verify  
#       - run: npm run test
