name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: npm ci
      - run: npm run test
