name: Running Cypress Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        
jobs:
  build:
    runs-on: self-hosted
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run test
#           start: npm start  
#       - run: npm install
#       - run: npx cypress verify  
#       - run: npm run test
